name: Github Actions Training
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building docker image"

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - name: deploy
        run: echo "deploying to k8s!"
